plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - - "@semantic-release/changelog"
      - changelogFile: CHANGELOG.md
    - - "@semantic-release/exec"
      - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
    - "@semantic-release/gitlab"
branches:
    - "master"
    - "+([0-9])?(.{+([0-9]),x}).x"
    - name: "alpha"
      prerelease: "alpha"
