{
 "title": "Storidge CIO",
 "description": "Dashboard that shows basic usage of the CIO Prometheus integrations.",
 "tags": [
  "swarm",
  "storidge"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Health",
   "type": "graph",
   "description": "Shows the number of nodes that are healthy, cordoned manually, or in maintenance mode (has an error that needs to be addressed)",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cio_cluster_nodes_count", "legendFormat": "Total" },
    { "expr": "cio_cluster_nodes_online", "legendFormat": "Healthy" },
    { "expr": "cio_cluster_nodes_cordoned", "legendFormat": "Cordoned" },
    { "expr": "cio_cluster_nodes_maintenance", "legendFormat": "Unhealthy" }
   ]
  },
  {
   "title": "Drive Health",
   "type": "graph",
   "description": "Counts of drives that are healthy, unhealthy, and available for adding to CIO via cioctl drive commands.",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cio_cluster_drives_online", "legendFormat": "Drives" },
    { "expr": "cio_cluster_drives_faulty", "legendFormat": "Faulty" }
   ]
  },
  {
   "title": "API Responses",
   "type": "graph",
   "description": "This panel shows what portions of requests to the API are returning successfully.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cio_api_calls_ok", "legendFormat": "200 OK" },
    {
     "expr": "io_api_calls_internal_server_error",
     "legendFormat": "500 ISE"
    },
    { "expr": "cio_api_calls_bad_request", "legendFormat": "400 Bad Request" },
    { "expr": "cio_api_calls_not_found", "legendFormat": "404 Not Found" },
    { "expr": "cio_api_calls_conflict", "legendFormat": "409 Conflict" }
   ]
  },
  { "title": "CIO Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Resource Utilization",
   "type": "gauge",
   "description": "Percentage utilization of CIO Cluster Resources. This is resources that have been allocated for use (provisioned) and in use. The amount of space free is also available. All units are in bytes.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cio_cluster_capacity_provisioned/cio_cluster_capacity_total*100",
     "legendFormat": "Capacity Provisioned"
    },
    {
     "expr": "cio_cluster_capacity_used/cio_cluster_capacity_total*100",
     "legendFormat": "Capacity Used"
    },
    {
     "expr": "cio_cluster_bw_provisioned/cio_cluster_bw_total*100",
     "legendFormat": "Bandwidth Provisioned"
    },
    {
     "expr": "cio_cluster_bw_used/cio_cluster_bw_total*100",
     "legendFormat": "Bandwidth Used"
    },
    {
     "expr": "cio_cluster_iops_provisioned/cio_cluster_iops_total*100",
     "legendFormat": "IOPS Provisioned"
    },
    {
     "expr": "cio_cluster_iops_used/cio_cluster_iops_total*100",
     "legendFormat": "IOPS Used"
    }
   ]
  },
  {
   "title": "MongoDB (vd0) Usage",
   "type": "graph",
   "description": "Sample of monitoring usage for a given application",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cio_volume_vd0_writes_completed",
     "legendFormat": "Writes Completed"
    }
   ]
  }
 ]
}