{
 "title": "Gitlab Runner",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "runner",
    "query": "label_values(ci_runner_errors, instance)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Runner Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitlab_runner_version_info" }
   ]
  },
  {
   "title": "Errors Total N",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitlab_runner_errors_total", "legendFormat": "{{runner}} {{level}}" }
   ]
  },
  {
   "title": "API Request Statuses Total N",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_api_request_statuses_total",
     "legendFormat": "{{job}} {{runner}}"
    }
   ]
  },
  {
   "title": "Limit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitlab_runner_limit", "legendFormat": "{{job}} {{runner}}" }
   ]
  },
  { "title": "Autoscaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Autoscaling Machine Creation Duration in seconds (bucket)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket",
     "legendFormat": "{{job}} {{executor}}"
    }
   ]
  },
  {
   "title": "Autoscaling Machine Creation Duration in Seconds (sum)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_autoscaling_machine_creation_duration_seconds_sum",
     "legendFormat": "{{job}} {{executor}}"
    }
   ]
  },
  {
   "title": "Autoscaling Machine Creation in seconds (count)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_autoscaling_machine_creation_duration_seconds_count",
     "legendFormat": "{{job}} {{executor}}"
    }
   ]
  },
  {
   "title": "Autoscaling Machine States",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_autoscaling_machine_states",
     "legendFormat": "{{job}} {{state}}"
    }
   ]
  },
  { "title": "Concurrency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Request Concurrency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_request_concurrency",
     "legendFormat": "{{job}} {{runner}}"
    }
   ]
  },
  {
   "title": "Concurrency Exceeded Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_request_concurrency_exceeded_total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Concurrent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitlab_runner_concurrent", "legendFormat": "{{job}}" }
   ]
  }
 ]
}