{
 "title": "Statping",
 "description": "Statping Grafana Dashboard",
 "tags": [
  "golang",
  "web"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(statping_service_online, instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(statping_service_online, service)"
   },
   {
    "name": "services",
    "query": "statping_service_online{instance=\"$instance\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Services Offline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "repeat": "services",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(statping_service_online{instance=\"$instance\"} == 0)"
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 3, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(statping_query{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{type}} - {{method}}"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "statping_database{instance=\"$instance\", metric=\"open_connections\"}",
     "legendFormat": "Open"
    },
    {
     "expr": "statping_database{instance=\"$instance\", metric=\"in_use_connections\"}",
     "legendFormat": "In Use"
    },
    {
     "expr": "statping_database{instance=\"$instance\", metric=\"idle_connections\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "statping_database{instance=\"$instance\", metric=\"max_open_connections\"}",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Services Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(statping_service_online{instance=\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "Service Request Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(statping_service_duration_sum{instance=\"$instance\", service=~\"$service\"}[$interval]) - rate(statping_service_duration_count{instance=\"$instance\", service=~\"$service\"}[$interval])"
    }
   ]
  },
  {
   "title": "Services Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(statping_service_online == 1)"
    }
   ]
  },
  {
   "title": "Services Offline",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(statping_service_online == 0)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(statping_service_failures{instance=\"$instance\"}[$interval])) by (method)"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{instance=\"$instance\"}[$interval])",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{instance=\"$instance\"}[$interval])",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{instance=\"$instance\"}[$interval])",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_heap_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_heap_released_bytes"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\"}",
     "legendFormat": "Routines"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=\"$instance\"} - go_memstats_other_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_other_sys_bytes"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_next_gc_bytes"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=\"$instance\"}[$interval]) - rate(go_memstats_frees_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "Objects"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_sys_bytes"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "go_gc_duration_seconds"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_stack_sys_bytes"
    }
   ]
  },
  {
   "title": "All HTTP Request Durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(statping_http_requests_duration_sum{instance=\"$instance\"}[$interval]) - rate(statping_http_requests_duration_count{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{method}} - {{url}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "go_memstats_alloc_bytes_total"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "repeat": "services",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(statping_query{instance=\"$instance\"}) by (method)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Service Failures",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "statping_service_failures{instance=\"$instance\", service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "statping_service_success{instance=\"$instance\", service=~\"$service\"}"
    },
    {
     "expr": "statping_service_failures{instance=\"$instance\", service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "HTTP Response Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(statping_http_response_bytes_sum{instance=\"$instance\"}[$interval]) - rate(statping_http_response_bytes_count{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{method}} - {{url}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "statping_service_failures{instance=\"$instance\"}",
     "legendFormat": "Service #{{service}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\"}",
     "legendFormat": "go_goroutines"
    }
   ]
  },
  {
   "title": "Service Latency Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(statping_service_latency_bucket{instance=\"$instance\"}[$interval])) by (le))"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{instance=\"$instance\"}[$interval])"
    }
   ]
  }
 ]
}